build_folder: build
output_folder: data
items:
  example_repo_item:
    git_url: https://github.com/temphia-contrib/example_repo_item
    branch: main
    build_cmd: "./build.sh"
    bprint_file: "./bprint.yaml"
  