# running locally in act
# act workflow_dispatch -W .github/workflows/build.yaml

on:
  workflow_dispatch:
    inputs:
      repo_item:
        description: 'single repo to build'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: build packages
        run: |
          go run . ${{ inputs.repo_item }}
      
      - name: Commit repo build output
        run: |
          git add .
          git config --global user.name 'bornjre'
          git config --global user.email 'bornjre@users.noreply.github.com'
          git commit -am "##  ${{ inputs.github.run_id }} # ${{ inputs.repo_item }}"
          git push