# running locally in act
# act workflow_dispatch -W .github/workflows/build.yaml

on:
  workflow_dispatch:
    inputs:
      repo_item:
        description: 'single repo to build'
        required: false
        type: string

jobs:
  android_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: build packages
        run: |
          go run . ${{ inputs.repo_item }}